Add Brazilian Portuguese translation
andyholmes/gnome-shell-extension-valent pull request #86
Opened 2023-11-03 00:55 UTC by fliperama00

2023-11-03 17:27 UTC, andyholmes requested changes

2023-11-03 17:27 UTC, andyholmes commented on po/LINGUAS
> +pt
Just make this `pt_BR` and then it looks good to me :slightly_smiling_face:

2023-11-04 03:16 UTC, fliperama00 commented
Should I just use the --fixup flag here or there is a better way?

2023-11-04 04:04 UTC, andyholmes commented
> Should I just use the --fixup flag here or is there a better way?

Just rename the file (`pt_BR.po`) and then you can squash to single commit.

2023-11-04 04:15 UTC, fliperama00 commented
Amazing. Thank you

2023-11-04 17:59 UTC, andyholmes approved these changes

2023-11-04 17:59 UTC, merged